In [169]:
import tensorflow as tf
import pandas as pd
import numpy as np

tf.set_random_seed(100)  # for reproducibility

In [170]:
data = np.loadtxt("/Users/cutei/Desktop/data.csv",delimiter=",")

In [171]:
print(data)

[[ 0.      12.89    13.12    ...  0.05366  0.2309   0.06915]
 [ 0.      14.96    19.1     ...  0.1489   0.2962   0.08472]
 [ 0.      12.94    16.17    ...  0.08388  0.3297   0.07834]
 ...
 [ 1.      21.1     20.52    ...  0.228    0.2268   0.07425]
 [ 1.      17.08    27.15    ...  0.1555   0.301    0.0906 ]
 [ 1.      27.42    26.27    ...  0.2625   0.2641   0.07427]]


In [172]:
y = data[0:,0]

In [134]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [173]:
x = data[0:,1:]

In [136]:
print(x)

[[1.289e+01 1.312e+01 8.189e+01 ... 5.366e-02 2.309e-01 6.915e-02]
 [1.496e+01 1.910e+01 9.703e+01 ... 1.489e-01 2.962e-01 8.472e-02]
 [1.294e+01 1.617e+01 8.318e+01 ... 8.388e-02 3.297e-01 7.834e-02]
 ...
 [2.110e+01 2.052e+01 1.381e+02 ... 2.280e-01 2.268e-01 7.425e-02]
 [1.708e+01 2.715e+01 1.112e+02 ... 1.555e-01 3.010e-01 9.060e-02]
 [2.742e+01 2.627e+01 1.869e+02 ... 2.625e-01 2.641e-01 7.427e-02]]


In [174]:
from sklearn.preprocessing import normalize
x = normalize(x)
#x = normalize(x, axis = 0, norm = 'max')

In [154]:
print(x)

[[1.64453642e-02 1.67388035e-02 1.04477182e-01 ... 6.84606858e-05
  2.94587632e-04 8.82231909e-05]
 [1.39403470e-02 1.77981703e-02 9.04165688e-02 ... 1.38751181e-04
  2.76011416e-04 7.89456015e-05]
 [1.65496982e-02 2.06807280e-02 1.06383609e-01 ... 1.07278879e-04
  4.21671987e-04 1.00193459e-04]
 ...
 [8.57087436e-03 8.33527687e-03 5.60965758e-02 ... 9.26141874e-05
  9.21267443e-05 3.01605413e-05]
 [8.95969751e-03 1.42421421e-02 5.83324569e-02 ... 8.15710166e-05
  1.57896309e-04 4.75262643e-05]
 [5.51189319e-03 5.28072335e-03 3.75701254e-02 ... 5.27670300e-05
  5.30886576e-05 1.49295517e-05]]


In [175]:
from sklearn.cross_validation import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)
x_test, x_val, y_test, y_val= train_test_split(x_test, y_test, test_size=0.5, random_state=1)


In [140]:
print(y_train)

[0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1.
 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.
 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0.
 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.

In [141]:
print(y_test)

[0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [176]:
#y reshape하기
y = np.reshape(y,(569,1))
y_train = np.reshape(y_train,(398,1))
y_test = np.reshape(y_test, (85,1))
y_val = np.reshape(y_val, (86,1))

In [177]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [178]:
##빈벡터만들기
new_x =tf.placeholder(tf.float32, shape=[None, 30])
new_y =tf.placeholder(tf.float32, shape=[None, 1])
w1 =tf.Variable(tf.random_normal([30,16]), name='weight1')
b1 =tf.Variable(tf.random_normal([16]), name='bias1')
w2 =tf.Variable(tf.random_normal([16,16]), name='weight2')
b2 =tf.Variable(tf.random_normal([16]), name='bias2')
w3 =tf.Variable(tf.random_normal([16,16]), name='weight3')
b3 =tf.Variable(tf.random_normal([16]), name='bias3')
w4 =tf.Variable(tf.random_normal([16,1]), name='weight4')
b4 =tf.Variable(tf.random_normal([1]), name='bias4')

 
L1 = tf.nn.relu(tf.matmul(new_x,w1)+b1)
L2 = tf.nn.relu(tf.matmul(L1,w2)+b2)
L3 = tf.nn.relu(tf.matmul(L2,w3)+b3)
hypothesis =tf.sigmoid(tf.matmul(L3,w4) +b4)


cost = -tf.reduce_mean(new_y*tf.log(hypothesis) + (1-new_y)*tf.log(1-hypothesis))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-3).minimize(cost)


# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, new_y), dtype=tf.float32))


In [179]:
    w1_hist = tf.summary.histogram("weight1",w1)
    b1_hist = tf.summary.histogram("bias1",b1)
    L1_hist = tf.summary.histogram("layer1",L1)
    w2_hist = tf.summary.histogram("weight2",w2)
    b2_hist = tf.summary.histogram("bias2",b2)
    L2_hist = tf.summary.histogram("layer2",L2)
    w3_hist = tf.summary.histogram("weight3",w3)
    b3_hist = tf.summary.histogram("bias3",b3)
    L3_hist = tf.summary.histogram("layer3",L3)
    w4_hist = tf.summary.histogram("weight4",w4)
    b4_hist = tf.summary.histogram("bias4",b4)

    hypothesis_hist = tf.summary.histogram("hypothesis",hypothesis)

In [180]:
    cost_summ = tf.summary.scalar("cost",cost)

In [182]:
# Launch graph
with tf.Session() as sess:
    
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/logs_t2")
    writer.add_graph(sess.graph)
    
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    
    for step in range(118600):
        cost_val, _ = sess.run([cost, optimizer], feed_dict={new_x: x_train, new_y: y_train})
        if step % 100 == 0:
            print(step, cost_val)
    
    
    # Accuracy report : test_set
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={new_x: x_train, new_y: y_train})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nTrain Accuracy: ", a)
            
    # Accuracy report : val_set
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={new_x: x_val, new_y: y_val})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\n Validation Accuracy: ", a)
    
     # Accuracy report : val_set
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={new_x: x_test, new_y: y_test})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\n test Accuracy: ", a)

0 0.92069733
100 0.5770002
200 0.50186986
300 0.4540524
400 0.41347325
500 0.3985867
600 0.38854146
700 0.379071
800 0.37136185
900 0.36480436
1000 0.3589428
1100 0.35358045
1200 0.34867248
1300 0.34414208
1400 0.33992285
1500 0.33598524
1600 0.3322655
1700 0.328738
1800 0.32538047
1900 0.322181
2000 0.31904736
2100 0.3159557
2200 0.31298032
2300 0.31019476
2400 0.30749425
2500 0.30489218
2600 0.30234122
2700 0.29992196
2800 0.2975958
2900 0.29533935
3000 0.29314655
3100 0.29103112
3200 0.28898022
3300 0.2869904
3400 0.28505576
3500 0.2831781
3600 0.2813606
3700 0.27959275
3800 0.27787182
3900 0.27619496
4000 0.2745606
4100 0.27296728
4200 0.27141303
4300 0.2698978
4400 0.26837665
4500 0.26684877
4600 0.26540962
4700 0.26399025
4800 0.26253948
4900 0.2609934
5000 0.25957036
5100 0.2582765
5200 0.2570275
5300 0.2558089
5400 0.25462702
5500 0.2534756
5600 0.25235265
5700 0.25125605
5800 0.2501852
5900 0.2491393
6000 0.2481115
6100 0.24711286
6200 0.24614707
6300 0.24520293
6400 0.2442794

49400 0.17814274
49500 0.17809345
49600 0.17804445
49700 0.17799537
49800 0.17794625
49900 0.17789729
50000 0.17784843
50100 0.1777997
50200 0.17775089
50300 0.17770211
50400 0.17765352
50500 0.17760487
50600 0.17755608
50700 0.17750768
50800 0.1774591
50900 0.17741072
51000 0.17736241
51100 0.17731409
51200 0.17726591
51300 0.17721774
51400 0.17716962
51500 0.17712156
51600 0.17707354
51700 0.17702547
51800 0.17697759
51900 0.17692943
52000 0.17688163
52100 0.17683372
52200 0.17678592
52300 0.17673814
52400 0.17669056
52500 0.17664292
52600 0.17659535
52700 0.17654778
52800 0.17650014
52900 0.17645285
53000 0.17640534
53100 0.17635803
53200 0.17631078
53300 0.17626338
53400 0.17621617
53500 0.17616881
53600 0.17612177
53700 0.17607458
53800 0.17602745
53900 0.17598057
54000 0.17593344
54100 0.17588638
54200 0.1758394
54300 0.17579238
54400 0.17574559
54500 0.1756988
54600 0.175652
54700 0.17560524
54800 0.17555857
54900 0.17551193
55000 0.17546518
55100 0.17541884
55200 0.17537218
553

98200 0.15824713
98300 0.15821482
98400 0.1581824
98500 0.15814993
98600 0.15811756
98700 0.15808529
98800 0.15805289
98900 0.15802054
99000 0.15798843
99100 0.15795612
99200 0.15792409
99300 0.15789174
99400 0.15785979
99500 0.15782766
99600 0.15779568
99700 0.15776385
99800 0.157732
99900 0.15770012
100000 0.15766804
100100 0.15763627
100200 0.15760466
100300 0.15757282
100400 0.15754096
100500 0.15750946
100600 0.15747789
100700 0.15744609
100800 0.15741463
100900 0.15738305
101000 0.15735157
101100 0.15732001
101200 0.15728866
101300 0.1572572
101400 0.15722574
101500 0.15719453
101600 0.15716317
101700 0.15713203
101800 0.15710041
101900 0.15706968
102000 0.15703821
102100 0.15700714
102200 0.15697585
102300 0.1569448
102400 0.15691397
102500 0.15688281
102600 0.1568518
102700 0.15682088
102800 0.15679017
102900 0.15675904
103000 0.15672827
103100 0.15669751
103200 0.15666664
103300 0.1566358
103400 0.15660511
103500 0.1565745
103600 0.15654394
103700 0.15651336
103800 0.15648308
